### ISSUE TITLE
Is it working on ionic v3

### ISSUE THREAD

**Issue by burhankaraman** [jonathanheilmann/heilbaum_photoswipe#8]
I did all the steps mentioned in the documentation but I get an error like the one below. Do you help me with this, where am I doing wrong?

Runtime Error
Uncaught (in promise): ReferenceError: PhotoSwipe is not defined ReferenceError: PhotoSwipe is not defined at HeilbaumPhotoswipeComponent.ngAfterViewInit (http://localhost:8100/build/vendor.js:68842:28) at callProviderLifecycles (http://localhost:8100/build/vendor.js:12782:18) at callElementProvidersLifecycles (http://localhost:8100/build/vendor.js:12753:13) at callLifecycleHooksChildrenFirst (http://localhost:8100/build/vendor.js:12737:17) at checkAndUpdateView (http://localhost:8100/build/vendor.js:13870:5) at callWithDebugContext (http://localhost:8100/build/vendor.js:15094:42) at Object.debugCheckAndUpdateView [as checkAndUpdateView] (http://localhost:8100/build/vendor.js:14631:12) at ViewRef_.detectChanges (http://localhost:8100/build/vendor.js:11654:18) at OverlayPortal.NavControllerBase._viewAttachToDOM (http://localhost:8100/build/vendor.js:55061:40) at OverlayPortal.NavControllerBase._transition (http://localhost:8100/build/vendor.js:55141:18)
Stack
Error: Uncaught (in promise): ReferenceError: PhotoSwipe is not defined
ReferenceError: PhotoSwipe is not defined
    at HeilbaumPhotoswipeComponent.ngAfterViewInit (http://localhost:8100/build/vendor.js:68842:28)
    at callProviderLifecycles (http://localhost:8100/build/vendor.js:12782:18)
    at callElementProvidersLifecycles (http://localhost:8100/build/vendor.js:12753:13)
    at callLifecycleHooksChildrenFirst (http://localhost:8100/build/vendor.js:12737:17)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:13870:5)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15094:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (http://localhost:8100/build/vendor.js:14631:12)
    at ViewRef_.detectChanges (http://localhost:8100/build/vendor.js:11654:18)
    at OverlayPortal.NavControllerBase._viewAttachToDOM (http://localhost:8100/build/vendor.js:55061:40)
    at OverlayPortal.NavControllerBase._transition (http://localhost:8100/build/vendor.js:55141:18)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:19174)
    at OverlayPortal.NavControllerBase._fireError (http://localhost:8100/build/vendor.js:54824:16)
    at OverlayPortal.NavControllerBase._failed (http://localhost:8100/build/vendor.js:54817:14)
    at http://localhost:8100/build/vendor.js:54864:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4983:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 8.9.4
OS Platform: macOS High Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75 Mobile/14E5239e Safari/602.1

**Comment by jonathanheilmann** [comment]
Without the code it's hard tu suggest, whats happening here, but I assume, that photoswipe is included after bundle.js and thus not known.

**Comment by burhankaraman** [comment]
Yes you re right, the photoswipe didn't included under build, but i found the solution. I put 
```
  "config": {
      "ionic_copy": "./config/copy.config.js"
  },
```
under `"description": "xxx",` key in package.json

before package.json was like below;
```
{
  "name": "xxx",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@agm/core": "^1.0.0-beta.2",
    "@agm/snazzy-info-window": "^1.0.0-beta.2",
    "@angular/animations": "^5.2.4",
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/geolocation": "^4.5.3",
    "@ionic-native/launch-navigator": "^4.5.3",
    "@ionic-native/social-sharing": "^4.5.3",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic-native/streaming-media": "^4.5.3",
    "@ionic/storage": "2.1.3",
    "angular2-moment": "^1.8.0",
    "angularfire2": "^4.0.0-rc.1",
    "com.hutchind.cordova.plugins.streamingmedia": "git+https://github.com/nchutchind/cordova-plugin-streaming-media.git",
    "cordova-android": "7.0.0",
    "cordova-custom-config": "^5.0.2",
    "cordova-ios": "4.5.4",
    "cordova-plugin-actionsheet": "^2.3.3",
    "cordova-plugin-device": "^2.0.1",
    "cordova-plugin-dialogs": "^2.0.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-streaming-media": "^1.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.2.1",
    "es6-promise-plugin": "^4.1.0",
    "firebase": "^3.6.6",
    "heilbaum-ionic-photoswipe": "^0.1.2",
    "ionic-angular": "3.9.2",
    "ionic-gallery-modal": "^0.2.7",
    "ionic2-zoom-area": "^1.0.14",
    "ionicons": "3.0.0",
    "moment": "^2.20.1",
    "ng2-lazyload-image": "^2.4.0",
    "rxjs": "5.5.2",
    "snazzy-info-window": "^1.1.1",
    "sw-toolbox": "3.6.0",
    "uk.co.workingedge.phonegap.plugin.launchnavigator": "^4.1.3",
    "videogular2": "^6.0.3",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.8",
    "@types/core-js": "^0.9.46",
    "@types/googlemaps": "^3.30.5",
    "typescript": "2.4.2"
  },
  "description": "xxx",
  "cordova": {
    "plugins": {
      "com.hutchind.cordova.plugins.streamingmedia": {},
      "cordova-plugin-x-socialsharing": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "xxx"
      },
      "uk.co.workingedge.phonegap.plugin.launchnavigator": {
        "LOCATION_USAGE_DESCRIPTION": "This app requires access to your location for navigation purposes"
      },
      "cordova-custom-config": {}
    },
    "platforms": [
      "android",
      "ios"
    ],
  "config": {
      "ionic_copy": "./config/copy.config.js"
  }
  }
}

```
After

```
{
  "name": "xxx",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@agm/core": "^1.0.0-beta.2",
    "@agm/snazzy-info-window": "^1.0.0-beta.2",
    "@angular/animations": "^5.2.4",
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/geolocation": "^4.5.3",
    "@ionic-native/launch-navigator": "^4.5.3",
    "@ionic-native/social-sharing": "^4.5.3",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic-native/streaming-media": "^4.5.3",
    "@ionic/storage": "2.1.3",
    "angular2-moment": "^1.8.0",
    "angularfire2": "^4.0.0-rc.1",
    "com.hutchind.cordova.plugins.streamingmedia": "git+https://github.com/nchutchind/cordova-plugin-streaming-media.git",
    "cordova-android": "7.0.0",
    "cordova-custom-config": "^5.0.2",
    "cordova-ios": "4.5.4",
    "cordova-plugin-actionsheet": "^2.3.3",
    "cordova-plugin-device": "^2.0.1",
    "cordova-plugin-dialogs": "^2.0.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-streaming-media": "^1.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.2.1",
    "es6-promise-plugin": "^4.1.0",
    "firebase": "^3.6.6",
    "heilbaum-ionic-photoswipe": "^0.1.2",
    "ionic-angular": "3.9.2",
    "ionic-gallery-modal": "^0.2.7",
    "ionic2-zoom-area": "^1.0.14",
    "ionicons": "3.0.0",
    "moment": "^2.20.1",
    "ng2-lazyload-image": "^2.4.0",
    "rxjs": "5.5.2",
    "snazzy-info-window": "^1.1.1",
    "sw-toolbox": "3.6.0",
    "uk.co.workingedge.phonegap.plugin.launchnavigator": "^4.1.3",
    "videogular2": "^6.0.3",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.8",
    "@types/core-js": "^0.9.46",
    "@types/googlemaps": "^3.30.5",
    "typescript": "2.4.2"
  },
  "description": "xxx",

  "cordova": {
    "plugins": {
      "com.hutchind.cordova.plugins.streamingmedia": {},
      "cordova-plugin-x-socialsharing": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "xxx"
      },
      "uk.co.workingedge.phonegap.plugin.launchnavigator": {
        "LOCATION_USAGE_DESCRIPTION": "This app requires access to your location for navigation purposes"
      },
      "cordova-custom-config": {}
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}
```
